version: '3'

services:
  build:
    image: orthanc-azure-blob-storage-plugin-sdk
    build:
      context: .
      dockerfile: docker/Dockerfile.ubuntu-18.04
      args:
        ORTHANC_VERSION: 1.3.1 
    volumes:
      - .:/src
    working_dir: /src
    environment:
      ORTHANC_ROOT: /bootstrap/Orthanc-1.3.1
      BUILD_DIR: /src/build
      INSTALL_DIR: /src/install
      VCPKG_DIR: /bootstrap/vcpkg
    command: /bin/bash build.sh